/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rpg;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Felipe Rabelo
 */
public class JanelaConfiguraItens extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConfiguraItens
     */
    public JanelaConfiguraItens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Item");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Description:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("STR:");

        jLabel4.setText("WIS:");

        jLabel5.setText("VIG:");

        jLabel6.setText("WIL:");

        jLabel7.setText("CON:");

        jLabel8.setText("INT:");

        jLabel9.setText("DEX:");

        jLabel10.setText("Type:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Equipment");
        jRadioButton1.setActionCommand("equip");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Weapon");
        jRadioButton2.setActionCommand("weapon");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Potion");
        jRadioButton3.setActionCommand("potion");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Custom");
        jRadioButton4.setActionCommand("custom");

        jLabel11.setText("Healing - HP:");

        jLabel12.setText("Healing - MP:");

        jLabel13.setText("Armor:");

        jLabel14.setText("Damage:");

        jLabel15.setText("Element:");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Neutral");

        jCheckBox2.setText("Fire");

        jCheckBox3.setText("Water");

        jCheckBox4.setText("Earth");

        jCheckBox5.setText("Wind");

        jCheckBox6.setText("Light");

        jCheckBox7.setText("Black");

        jLabel17.setText("Fire:");

        jLabel18.setText("Water:");

        jLabel19.setText("Earth:");

        jLabel20.setText("%");

        jLabel21.setText("%");

        jLabel22.setText("%");

        jLabel23.setText("Wind:");

        jLabel24.setText("Light:");

        jLabel25.setText("Black:");

        jTextField16.setPreferredSize(new java.awt.Dimension(65, 21));

        jLabel26.setText("%");

        jLabel28.setText("%");

        jLabel27.setText("%");

        jLabel16.setText("Skill - ");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Yes");

        jLabel29.setText("/");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("No");

        jLabel30.setText("Skill name:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField19))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel19))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField15)
                                        .addComponent(jTextField14)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField18))
                                    .addComponent(jTextField11)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel24)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField17)
                                            .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)))
                                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel27))
                                        .addGap(46, 46, 46))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7))))
                .addContainerGap())
            .addComponent(jSeparator2)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jCheckBox1))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel12)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBox3)
                    .addComponent(jLabel13)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBox4)
                    .addComponent(jLabel14)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBox5)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBox6)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jCheckBox7)
                    .addComponent(jLabel19)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jRadioButton5)
                    .addComponent(jLabel29)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jTextField19.setEditable(false);
        jTextField19.setBackground(Color.LIGHT_GRAY);
        ChangeListener skillChangeListener = (ChangeEvent change) -> {
            AbstractButton aButton = (AbstractButton)change.getSource();
            ButtonModel aModel = aButton.getModel();
            boolean selected = aModel.isSelected();
            
            if (selected) {
                jTextField19.setEditable(true);
                jTextField19.setBackground(Color.WHITE);
            } else {
                jTextField19.setEditable(false);
                jTextField19.setBackground(Color.LIGHT_GRAY);
                jTextField19.setText("");
            }
        };
        jRadioButton5.addChangeListener(skillChangeListener);
        
        ChangeListener equipmentChangeListener = (ChangeEvent change) -> {
            AbstractButton aButton = (AbstractButton)change.getSource();
            ButtonModel aModel = aButton.getModel();
            boolean selected = aModel.isSelected();
            
            if (selected) {
                jTextField9.setEditable(false);
                jTextField9.setBackground(Color.LIGHT_GRAY);
                jTextField9.setText("");
                jTextField10.setEditable(false);
                jTextField10.setBackground(Color.LIGHT_GRAY);
                jTextField10.setText("");
                
                jTextField12.setEditable(false);
                jTextField12.setBackground(Color.LIGHT_GRAY);
                jTextField12.setText("");
            } else {
                jTextField9.setEditable(true);
                jTextField9.setBackground(Color.WHITE);
                jTextField9.setText("");
                jTextField10.setEditable(true);
                jTextField10.setBackground(Color.WHITE);
                jTextField10.setText(""); 
                
                jTextField12.setEditable(true);
                jTextField12.setBackground(Color.WHITE);
                jTextField12.setText("");
            }
        };
        jRadioButton1.addChangeListener(equipmentChangeListener);
        
        ChangeListener weaponChangeListener = (ChangeEvent change) -> {
            AbstractButton aButton = (AbstractButton)change.getSource();
            ButtonModel aModel = aButton.getModel();
            boolean selected = aModel.isSelected();
            
            if (selected) {
                jTextField9.setEditable(false);
                jTextField9.setBackground(Color.LIGHT_GRAY);
                jTextField10.setText("");
                jTextField10.setEditable(false);
                jTextField10.setBackground(Color.LIGHT_GRAY);
                jTextField10.setText("");
                
                jTextField11.setEditable(false);
                jTextField11.setBackground(Color.LIGHT_GRAY);
                jTextField11.setText("");
                
                jTextField13.setEditable(false);
                jTextField13.setBackground(Color.LIGHT_GRAY);
                jTextField13.setText("");
                jTextField14.setEditable(false);
                jTextField14.setBackground(Color.LIGHT_GRAY);
                jTextField14.setText("");
                jTextField15.setEditable(false);
                jTextField15.setBackground(Color.LIGHT_GRAY);
                jTextField15.setText("");
                jTextField16.setEditable(false);
                jTextField16.setBackground(Color.LIGHT_GRAY);
                jTextField16.setText("");
                jTextField17.setEditable(false);
                jTextField17.setBackground(Color.LIGHT_GRAY);
                jTextField17.setText("");
                jTextField18.setEditable(false);
                jTextField18.setBackground(Color.LIGHT_GRAY);
                jTextField18.setText("");
            } else {
                jTextField9.setEditable(true);
                jTextField9.setBackground(Color.WHITE);
                jTextField10.setText("");
                jTextField10.setEditable(true);
                jTextField10.setBackground(Color.WHITE);
                jTextField10.setText("");
                
                jTextField11.setEditable(true);
                jTextField11.setBackground(Color.WHITE);
                jTextField11.setText("");
                
                jTextField13.setEditable(true);
                jTextField13.setBackground(Color.WHITE);
                jTextField13.setText("");
                jTextField14.setEditable(true);
                jTextField14.setBackground(Color.WHITE);
                jTextField14.setText("");
                jTextField15.setEditable(true);
                jTextField15.setBackground(Color.WHITE);
                jTextField15.setText("");
                jTextField16.setEditable(true);
                jTextField16.setBackground(Color.WHITE);
                jTextField16.setText("");
                jTextField17.setEditable(true);
                jTextField17.setBackground(Color.WHITE);
                jTextField17.setText("");
                jTextField18.setEditable(true);
                jTextField18.setBackground(Color.WHITE);
                jTextField18.setText("");
            }
        };
        jRadioButton2.addChangeListener(weaponChangeListener);
        
        ChangeListener potionChangeListener = (ChangeEvent change) -> {
            AbstractButton aButton = (AbstractButton)change.getSource();
            ButtonModel aModel = aButton.getModel();
            boolean selected = aModel.isSelected();
            
            if (selected) {
                jTextField2.setEditable(false);
                jTextField2.setBackground(Color.LIGHT_GRAY);
                jTextField2.setText("");
                jTextField3.setEditable(false);
                jTextField3.setBackground(Color.LIGHT_GRAY);
                jTextField3.setText("");
                jTextField4.setEditable(false);
                jTextField4.setBackground(Color.LIGHT_GRAY);
                jTextField4.setText("");
                jTextField5.setEditable(false);
                jTextField5.setBackground(Color.LIGHT_GRAY);
                jTextField5.setText("");
                jTextField6.setEditable(false);
                jTextField6.setBackground(Color.LIGHT_GRAY);
                jTextField6.setText("");
                jTextField7.setEditable(false);
                jTextField7.setBackground(Color.LIGHT_GRAY);
                jTextField7.setText("");
                jTextField8.setEditable(false);
                jTextField8.setBackground(Color.LIGHT_GRAY);
                jTextField8.setText("");
                
                jTextField11.setEditable(false);
                jTextField11.setBackground(Color.LIGHT_GRAY);
                jTextField11.setText("");
                jTextField12.setEditable(false);
                jTextField12.setBackground(Color.LIGHT_GRAY);
                jTextField12.setText("");
                
                jTextField13.setEditable(false);
                jTextField13.setBackground(Color.LIGHT_GRAY);
                jTextField13.setText("");
                jTextField14.setEditable(false);
                jTextField14.setBackground(Color.LIGHT_GRAY);
                jTextField14.setText("");
                jTextField15.setEditable(false);
                jTextField15.setBackground(Color.LIGHT_GRAY);
                jTextField15.setText("");
                jTextField16.setEditable(false);
                jTextField16.setBackground(Color.LIGHT_GRAY);
                jTextField16.setText("");
                jTextField17.setEditable(false);
                jTextField17.setBackground(Color.LIGHT_GRAY);
                jTextField17.setText("");
                jTextField18.setEditable(false);
                jTextField18.setBackground(Color.LIGHT_GRAY);
                jTextField18.setText("");
            } else {
                jTextField2.setEditable(true);
                jTextField2.setBackground(Color.WHITE);
                jTextField2.setText("");
                jTextField3.setEditable(true);
                jTextField3.setBackground(Color.WHITE);
                jTextField3.setText("");
                jTextField4.setEditable(true);
                jTextField4.setBackground(Color.WHITE);
                jTextField4.setText("");
                jTextField5.setEditable(true);
                jTextField5.setBackground(Color.WHITE);
                jTextField5.setText("");
                jTextField6.setEditable(true);
                jTextField6.setBackground(Color.WHITE);
                jTextField6.setText("");
                jTextField7.setEditable(true);
                jTextField7.setBackground(Color.WHITE);
                jTextField7.setText("");
                jTextField8.setEditable(true);
                jTextField8.setBackground(Color.WHITE);
                jTextField8.setText("");
                
                jTextField11.setEditable(true);
                jTextField11.setBackground(Color.WHITE);
                jTextField11.setText("");
                jTextField12.setEditable(true);
                jTextField12.setBackground(Color.WHITE);
                jTextField12.setText("");
                
                jTextField13.setEditable(true);
                jTextField13.setBackground(Color.WHITE);
                jTextField13.setText("");
                jTextField14.setEditable(true);
                jTextField14.setBackground(Color.WHITE);
                jTextField14.setText("");
                jTextField15.setEditable(true);
                jTextField15.setBackground(Color.WHITE);
                jTextField15.setText("");
                jTextField16.setEditable(true);
                jTextField16.setBackground(Color.WHITE);
                jTextField16.setText("");
                jTextField17.setEditable(true);
                jTextField17.setBackground(Color.WHITE);
                jTextField17.setText("");
                jTextField18.setEditable(true);
                jTextField18.setBackground(Color.WHITE);
                jTextField18.setText("");
            }
        };
        jRadioButton3.addChangeListener(potionChangeListener);
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (evt.getSource() == jButton2) {
            this.dispose();
            
            JanelaConfiguracao config = new JanelaConfiguracao ();
            config.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            config.setSize(250, 500);
            config.setLocation(500, 3);
            config.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (evt.getSource() == jButton1) {
            String name = jTextField1.getText();
            int [] type = {0, 0, 0, 0};
            switch (buttonGroup1.getSelection().getActionCommand()) {
                case "equip":
                    type[0] = 1;
                    break;
                case "weapon":
                    type[1] = 1;
                    break;
                case "potion":
                    type[2] = 1;
                    break;
                case "custom":
                    type[3] = 1;
                    break;
            }
            String description = "";
            if (!jTextArea1.getText().equals("")) {description = jTextArea1.getText();}
            int str = 0;
            if (!jTextField2.getText().equals("")) {str = Integer.valueOf(jTextField2.getText());}
            int wis = 0;
            if (!jTextField3.getText().equals("")) {wis = Integer.valueOf(jTextField3.getText());}
            int vig = 0;
            if (!jTextField4.getText().equals("")) {vig = Integer.valueOf(jTextField4.getText());}
            int wil = 0;
            if (!jTextField5.getText().equals("")) {wil = Integer.valueOf(jTextField5.getText());}
            int con = 0;
            if (!jTextField6.getText().equals("")) {con = Integer.valueOf(jTextField6.getText());}
            int Int = 0;
            if (!jTextField7.getText().equals("")) {Int = Integer.valueOf(jTextField7.getText());}
            int dex = 0;
            if (!jTextField8.getText().equals("")) {dex = Integer.valueOf(jTextField8.getText());}
            int hp = 0;
            if (!jTextField9.getText().equals("")) {hp = Integer.valueOf(jTextField9.getText());}
            int mp = 0;
            if (!jTextField10.getText().equals("")) {mp = Integer.valueOf(jTextField10.getText());}
            int arm = 0;
            if (!jTextField11.getText().equals("")) {arm = Integer.valueOf(jTextField11.getText());}
            int dam = 0;
            if (!jTextField12.getText().equals("")) {dam = Integer.valueOf(jTextField12.getText());}
            int [] resistence = new int [6];
            resistence[0] = 0;
            if (!jTextField13.getText().equals("")) {resistence[0] = Integer.valueOf(jTextField13.getText());}
            resistence[1] = 0;
            if (!jTextField14.getText().equals("")) {resistence[1] = Integer.valueOf(jTextField14.getText());}
            resistence[2] = 0;
            if (!jTextField15.getText().equals("")) {resistence[2] = Integer.valueOf(jTextField15.getText());}
            resistence[3] = 0;
            if (!jTextField16.getText().equals("")) {resistence[3] = Integer.valueOf(jTextField16.getText());}
            resistence[4] = 0;
            if (!jTextField17.getText().equals("")) {resistence[4] = Integer.valueOf(jTextField17.getText());}
            resistence[5] = 0;
            if (!jTextField18.getText().equals("")) {resistence[5] = Integer.valueOf(jTextField18.getText());}
            int [] element = {0, 0, 0, 0, 0, 0, 0};
            if (jCheckBox1.isSelected()) {element[0] = 1;}
            if (jCheckBox2.isSelected()) {element[1] = 1;}
            if (jCheckBox3.isSelected()) {element[2] = 1;}
            if (jCheckBox4.isSelected()) {element[3] = 1;}
            if (jCheckBox5.isSelected()) {element[4] = 1;}
            if (jCheckBox6.isSelected()) {element[5] = 1;}
            if (jCheckBox7.isSelected()) {element[6] = 1;}
            String skill = "";
            if (!jTextField19.getText().equals("")) {skill = jTextField19.getText();}
            
            try {
                Iten iten = new Iten ();
                iten.setName(name);iten.setType(type);iten.setDescription(description);
                iten.setSTR(str);iten.setWIS(wis);iten.setVIG(vig);iten.setWIL(wil);
                iten.setCON(con);iten.setINT(Int);iten.setDEX(dex);iten.setArm(arm);
                iten.setDam(dam);iten.setResistence(resistence);iten.setElement(element);
                iten.setSkill(skill);
                
                iten.gravaItem();
            } catch (IOException ex) {
                Logger.getLogger(JanelaConfiguraItens.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaConfiguraItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaConfiguraItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaConfiguraItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaConfiguraItens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaConfiguraItens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
